apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql-container
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: YWRtaW4xMjMK
  MYSQL_DATABASE: bmFzYWxvZ2luCg==
  MYSQL_PASSWORD: YWRtaW4K
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service-container
        image: nasablog.azurecr.io/nasa-blog-auth-service:latest
        ports:
        - containerPort: 5001
        envFrom:
        - configMapRef:
            name: auth-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  API_KEY: RzFhRVg2bjA4Z1VKd0pyMm1rdk5Bc2dSYmQyaDl6UUJYTjdDQWNURgo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apod-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apod-service
  template:
    metadata:
      labels:
        app: apod-service
    spec:
      containers:
      - name: apod-service-container
        image: nasablog.azurecr.io/nasa-blog-apod-service:latest
        ports:
        - containerPort: 5002
        envFrom:
        - configMapRef:
            name: apod-service-config
---
apiVersion: v1
kind: Service
metadata:
  name: apod-service-service
spec:
  selector:
    app: apod-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apod-service-config
data:
  API_KEY: RzFhRVg2bjA4Z1VKd0pyMm1rdk5Bc2dSYmQyaDl6UUJYTjdDQWNURgo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway-container
        image: nasablog.azurecr.io/nasa-blog-api-gateway:latest
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: api-gateway-config
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data: 
  API_KEY: RzFhRVg2bjA4Z1VKd0pyMm1rdk5Bc2dSYmQyaDl6UUJYTjdDQWNURgo=